### ISSUE TITLE
how to solve "Error in styleCharWidths[[i]] : subscript out of bounds"

### ISSUE THREAD

**Issue by GeraldCNelson** [awalker89/openxlsx#71] opened 2015-03-03 19:48 UTC
I have a longish script that computes some data frames, creates a workbook and adds the data frames as sheets. I want to use addStyle to adjust the styles of say numbers to not be generic. The script runs with no errors until I get to 
*saveWorkbook(wb, NutfileName, overwrite = TRUE)* 
which fails with 
*Error in styleCharWidths[[i]] : subscript out of bounds*

I can usually track down the addStyle command such as in the following but can't always figure out what the problem is

*numStyle <- createStyle(numFmt = "0.000")
writeData(wb, temp, sheet=pcCons, startRow=1, startCol=1, rowNames = FALSE)
addStyle(wb, sheet=pcCons, style=numStyle, rows = 2:nrow(temp), cols=4:ncol(temp), gridExpand = TRUE)*

It would be nice if addStyle would fail immediately rather than only when saveWorkbook is run. And a bit more useful error message would help too.

**Comment by awalker89** [comment] 2015-03-04 08:31
This is a bug in openxlsx stemming from setting the column widths to "auto"

Please update to the most recent version of openxlsx on github
Please send me your sessionInfo()
Please send me a small example I can run on my own maching which reproduces this error?

If it's easier you can email this directly to me at Alexander.Walker1989@gmail.com

**Comment by GeraldCNelson** [comment] 2015-03-04 22:53
Alex, I have for now commented out all the use of ³auto² widths and the
script runs fine. 

But when I open the spreadsheet I am told there is an error in it. I select
repair and the file looks fine. Here is the log of what was repaired.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<recoveryLog 
xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main
<http://schemas.openxmlformats.org/spreadsheetml/2006/main>
"><logFileName>Repair Result to IND.NoCC.MidGDPMidPop.nutOutput
03248.xml</logFileName><summary>Errors were detected in file 'Macintosh
HD:Users:gcn:Documents:workspace:nutrient-modeling:results:IND.NoCC.MidGDPMi
dPop.nutOutput.xlsx'</summary><repairedRecords summary="Following is a list
of repairs:"><repairedRecord>Repaired Records: Cell information from
/xl/worksheets/sheet31.xml</repairedRecord></repairedRecords></recoveryLog>




Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
http://bit.ly/1arho7d




From:  Alex <notifications@github.com>
Reply-To:  awalker89/openxlsx
<reply+007d44b2d415372cb0e91ff6eedaf6b9e6814ec7bc648eb392cf00000001110e84d79
2a169ce038edfc2@reply.github.com>
Date:  Wednesday, March 4, 2015 at 1:31 AM
To:  awalker89/openxlsx <openxlsx@noreply.github.com>
Cc:  Gerald Nelson <nelson.gerald.c@gmail.com>
Subject:  Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
subscript out of bounds" (#71)


This is a bug in openxlsx stemming from setting the column widths to "auto"

Please update to the most recent version of openxlsx on github
Please send me your sessionInfo()
Please send me a small example I can run on my own maching which reproduces
this error?

If it's easier you can email this directly to me at
Alexander.Walker1989@gmail.com

‹
Reply to this email directly or view it on GitHub
<https://github.com/awalker89/openxlsx/issues/71#issuecomment-77116055> .

**Comment by awalker89** [comment] 2015-03-05 10:58
Thanks for sending this through. Unfortunately I cannot replicate your
error yet.
To completely run the short example I still need the Excel
file "NutrientNames.xlsx".

If you are happy to send this through please do so.


As for the error in sheet 31. If it does not contain any confidential
information please send through the corrupt xlsx file (prior to selecting
repair) and I can look in to what is being repaired.

If you are not comfortable sending the entire excel file to me you can
unzip the xlsx file and send me the XML file corresponding to sheet31 "
/xl/worksheets/sheet31.xml".

Thanks,
Alex

**Comment by awalker89** [comment] 2015-03-05 11:18
46f741798a033acfc1455b6522379d0f8591c1dc fixes the logical subsetting error. So don't worry about sending me  "NutrientNames.xlsx".

I will look into the sheet31 error if you send me anything through.

**Comment by GeraldCNelson** [comment] 2015-03-05 14:50
Alex, Apologies for missing that file! I’m attaching it in case you still
want to use it.

I just downloaded the latest openxlsx from github and reran my script.

I’m attaching the resulting xlsx file that has the corrupt xlsx message.

Thanks, Jerry



Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
http://bit.ly/1arho7d




From:  Alex <notifications@github.com>
Reply-To:  awalker89/openxlsx
<reply+007d44b298bc4ebbe94ca0e3190ced21daf4d99bf07e092492cf00000001110ff8d29
2a169ce038edfc2@reply.github.com>
Date:  Thursday, March 5, 2015 at 3:58 AM
To:  awalker89/openxlsx <openxlsx@noreply.github.com>
Cc:  Gerald Nelson <nelson.gerald.c@gmail.com>
Subject:  Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
subscript out of bounds" (#71)

Thanks for sending this through. Unfortunately I cannot replicate your
error yet.
To completely run the short example I still need the Excel
file "NutrientNames.xlsx".

If you are happy to send this through please do so.


As for the error in sheet 31. If it does not contain any confidential
information please send through the corrupt xlsx file (prior to selecting
repair) and I can look in to what is being repaired.

If you are not comfortable sending the entire excel file to me you can
unzip the xlsx file and send me the XML file corresponding to sheet31 "
/xl/worksheets/sheet31.xml".

Thanks,
Alex



On 5 March 2015 at 09:53, Gerald Charles Nelson <notifications@github.com>
wrote:

> Alex, I have for now commented out all the use of ³auto² widths and the
> script runs fine.
>
> But when I open the spreadsheet I am told there is an error in it. I select
> repair and the file looks fine. Here is the log of what was repaired.
>
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
>
> <recoveryLog
> xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main
> <http://schemas.openxmlformats.org/spreadsheetml/2006/main>
> "><logFileName>Repair Result to IND.NoCC.MidGDPMidPop.nutOutput
> 03248.xml</logFileName><summary>Errors were detected in file 'Macintosh
>
> HD:Users:gcn:Documents:workspace:nutrient-modeling:results:IND.NoCC.MidGDPMi
> dPop.nutOutput.xlsx'</summary><repairedRecords summary="Following is a list
> of repairs:"><repairedRecord>Repaired Records: Cell information from
> /xl/worksheets/sheet31.xml</repairedRecord></repairedRecords></recoveryLog>
>
>
>
>
> Gerald C. Nelson
> Professor Emeritus, UIUC
> +1 217-390-7888 (cell)
> +1 970-639-2079 (land line)
> http://bit.ly/1arho7d
>
>
>
>
> From: Alex <notifications@github.com>
> Reply-To: awalker89/openxlsx
>
> <reply+007d44b2d415372cb0e91ff6eedaf6b9e6814ec7bc648eb392cf00000001110e84d79
> 2a169ce038edfc2@reply.github.com>
> Date: Wednesday, March 4, 2015 at 1:31 AM
> To: awalker89/openxlsx <openxlsx@noreply.github.com>
> Cc: Gerald Nelson <nelson.gerald.c@gmail.com>
> Subject: Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
> subscript out of bounds" (#71)
>
>
> This is a bug in openxlsx stemming from setting the column widths to "auto"
>
> Please update to the most recent version of openxlsx on github
> Please send me your sessionInfo()
> Please send me a small example I can run on my own maching which reproduces
> this error?
>
> If it's easier you can email this directly to me at
> Alexander.Walker1989@gmail.com
>
> ‹
> Reply to this email directly or view it on GitHub
> <https://github.com/awalker89/openxlsx/issues/71#issuecomment-77116055> .
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awalker89/openxlsx/issues/71#issuecomment-77268444>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/awalker89/openxlsx/issues/71#issuecomment-77344773> .

**Comment by awalker89** [comment] 2015-03-07 00:12
Hi Jerry,

Thank's for getting back to me - your email doesn't appear to have any
attachments?

Thanks,
Alex

**Comment by GeraldCNelson** [comment] 2015-03-07 00:29
Alex, I must have been having a senior moment. This one definitely has an
xlsx file attached. It has the error message when I open it.

Regards,
Jerry


Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
http://bit.ly/1arho7d




From:  Alex <notifications@github.com>
Reply-To:  awalker89/openxlsx
<reply+007d44b2475387a0d10fbefb84446e7751c27e901c7455ea92cf000000011112047c9
2a169ce038edfc2@reply.github.com>
Date:  Friday, March 6, 2015 at 5:12 PM
To:  awalker89/openxlsx <openxlsx@noreply.github.com>
Cc:  Gerald Nelson <nelson.gerald.c@gmail.com>
Subject:  Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
subscript out of bounds" (#71)

Hi Jerry,

Thank's for getting back to me - your email doesn't appear to have any
attachments?

Thanks,
Alex



On 6 March 2015 at 01:50, Gerald Charles Nelson <notifications@github.com>
wrote:

> Alex, Apologies for missing that file! I’m attaching it in case you still
> want to use it.
>
> I just downloaded the latest openxlsx from github and reran my script.
>
> I’m attaching the resulting xlsx file that has the corrupt xlsx message.
>
> Thanks, Jerry
>
>
>
> Gerald C. Nelson
> Professor Emeritus, UIUC
> +1 217-390-7888 (cell)
> +1 970-639-2079 (land line)
> http://bit.ly/1arho7d
>
>
>
>
> From: Alex <notifications@github.com>
> Reply-To: awalker89/openxlsx
>
> <reply+007d44b298bc4ebbe94ca0e3190ced21daf4d99bf07e092492cf00000001110ff8d29
> 2a169ce038edfc2@reply.github.com>
> Date: Thursday, March 5, 2015 at 3:58 AM
> To: awalker89/openxlsx <openxlsx@noreply.github.com>
> Cc: Gerald Nelson <nelson.gerald.c@gmail.com>
> Subject: Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
> subscript out of bounds" (#71)
>
> Thanks for sending this through. Unfortunately I cannot replicate your
> error yet.
> To completely run the short example I still need the Excel
> file "NutrientNames.xlsx".
>
> If you are happy to send this through please do so.
>
>
> As for the error in sheet 31. If it does not contain any confidential
> information please send through the corrupt xlsx file (prior to selecting
> repair) and I can look in to what is being repaired.
>
> If you are not comfortable sending the entire excel file to me you can
> unzip the xlsx file and send me the XML file corresponding to sheet31 "
> /xl/worksheets/sheet31.xml".
>
> Thanks,
> Alex
>
>
>
> On 5 March 2015 at 09:53, Gerald Charles Nelson <notifications@github.com>
> wrote:
>
> > Alex, I have for now commented out all the use of ³auto² widths and the
> > script runs fine.
> >
> > But when I open the spreadsheet I am told there is an error in it. I
> select
> > repair and the file looks fine. Here is the log of what was repaired.
> >
> > <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> >
> > <recoveryLog
> > xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main
> > <http://schemas.openxmlformats.org/spreadsheetml/2006/main>
> > "><logFileName>Repair Result to IND.NoCC.MidGDPMidPop.nutOutput
> > 03248.xml</logFileName><summary>Errors were detected in file 'Macintosh
> >
> >
> HD:Users:gcn:Documents:workspace:nutrient-modeling:results:IND.NoCC.MidGDPMi
> > dPop.nutOutput.xlsx'</summary><repairedRecords summary="Following is a
> list
> > of repairs:"><repairedRecord>Repaired Records: Cell information from
> >
> /xl/worksheets/sheet31.xml</repairedRecord></repairedRecords></recoveryLog>
> >
> >
> >
> >
> > Gerald C. Nelson
> > Professor Emeritus, UIUC
> > +1 217-390-7888 (cell)
> > +1 970-639-2079 (land line)
> > http://bit.ly/1arho7d
> >
> >
> >
> >
> > From: Alex <notifications@github.com>
> > Reply-To: awalker89/openxlsx
> >
> >
> <reply+007d44b2d415372cb0e91ff6eedaf6b9e6814ec7bc648eb392cf00000001110e84d79
> > 2a169ce038edfc2@reply.github.com>
> > Date: Wednesday, March 4, 2015 at 1:31 AM
> > To: awalker89/openxlsx <openxlsx@noreply.github.com>
> > Cc: Gerald Nelson <nelson.gerald.c@gmail.com>
> > Subject: Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
> > subscript out of bounds" (#71)
> >
> >
> > This is a bug in openxlsx stemming from setting the column widths to
> "auto"
> >
> > Please update to the most recent version of openxlsx on github
> > Please send me your sessionInfo()
> > Please send me a small example I can run on my own maching which
> reproduces
> > this error?
> >
> > If it's easier you can email this directly to me at
> > Alexander.Walker1989@gmail.com
> >
> > ‹
> > Reply to this email directly or view it on GitHub
> > <https://github.com/awalker89/openxlsx/issues/71#issuecomment-77116055>
> .
> >
> >
> >
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/awalker89/openxlsx/issues/71#issuecomment-77268444>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awalker89/openxlsx/issues/71#issuecomment-77344773> .
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awalker89/openxlsx/issues/71#issuecomment-77376366>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/awalker89/openxlsx/issues/71#issuecomment-77659727> .

**Comment by awalker89** [comment] 2015-03-07 01:09
Hi Jerry,

It appears github is removing the attachments. Can you please email the
xlsx file directly to Alexander.Walker1989@gmail.com.

Thanks,
Alex

**Comment by awalker89** [comment] 2015-03-07 05:50
Thanks for sending the files through. The bug was related to the NaN values, this should be fixed now.

Please update with 
```
devtools::install_github("awalker89/openxlsx")
```

**Comment by GeraldCNelson** [comment] 2015-03-07 17:39
Alex,

The new fix got rid of the xlsx error. But I¹m getting a new error. I have a
code snippet below with the error message. Happy to send the complete code.
The data being written is a data frame with two character variables ­
sheetNameList and sheetNameDesc. These start out as lists and are converted
to a data.frame in the code below. Should I use something other than lists
to create the data frame?


> #add sheet with info about each of the worksheets
> sheetNameMeta <-as.data.frame(cbind(sheetNameList,sheetNameDesc))
> addWorksheet(wb, sheetName="sheetInfo")
> writeData(wb, sheetNameMeta, sheet="sheetInfo", startRow=1, startCol=1,
rowNames = FALSE, colNames = FALSE)
Error in is.nan(df[[i]]) : default method not implemented for type 'list'


Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
http://bit.ly/1arho7d




From:  Alex <notifications@github.com>
Reply-To:  awalker89/openxlsx
<reply+007d44b255bcb360f64781e47bdc891572d389b021260d8592cf000000011112539d9
2a169ce038edfc2@reply.github.com>
Date:  Friday, March 6, 2015 at 10:50 PM
To:  awalker89/openxlsx <openxlsx@noreply.github.com>
Cc:  Gerald Nelson <nelson.gerald.c@gmail.com>
Subject:  Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
subscript out of bounds" (#71)


Thanks for sending the files through. The bug was related to the NaN values,
this should be fixed now.

Please update with 
devtools::install_github("awalker89/openxlsx")
‹
Reply to this email directly or view it on GitHub
<https://github.com/awalker89/openxlsx/issues/71#issuecomment-77675208> .

**Comment by awalker89** [comment] 2015-03-07 23:26
Hi Jerry,

Yeah this is a weird one because the columns of the data.frame are themselves lists (rather than numeric, character, factor, etc...).

openxlsx just happened to handle this correctly but now it's failing on the check for NaN values.  

I suggest something like this

```
sheetNameMeta <- data.frame("sheetNameList" = unlist(sheetNameList),
                            "sheetNameDesc" = unlist(sheetNameDesc))
```

This will make sheetNameMeta  a more 'usual' data.frame.

**Comment by GeraldCNelson** [comment] 2015-03-08 23:06
Alex,

The list approach was probably not the best. I have gone simpler and
everything works fine.

Thanks for all your help with this!
Jerry


Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
http://bit.ly/1arho7d




From:  Alex <notifications@github.com>
Reply-To:  awalker89/openxlsx
<reply+007d44b2f411473c0d0e2ec0fd4ead745d6089ab2201b49d92cf0000000111134b289
2a169ce038edfc2@reply.github.com>
Date:  Saturday, March 7, 2015 at 5:26 PM
To:  awalker89/openxlsx <openxlsx@noreply.github.com>
Cc:  Gerald Nelson <nelson.gerald.c@gmail.com>
Subject:  Re: [openxlsx] how to solve "Error in styleCharWidths[[i]] :
subscript out of bounds" (#71)


Hi Jerry,

Yeah this is a weird one because the columns of the data.frame are
themselves lists (rather than numeric, character, factor, etc...).

openxlsx just happened to handle this correctly but now it's failing on the
check for NaN values.

I suggest something like this
sheetNameMeta <- data.frame("sheetNameList" = unlist(sheetNameList),
                            "sheetNameDesc" = unlist(sheetNameDesc))
This will make sheetNameMeta  a more 'usual' data.frame.

‹
Reply to this email directly or view it on GitHub
<https://github.com/awalker89/openxlsx/issues/71#issuecomment-77716155> .

**Closed** 2015-03-14 03:50 UTC
