### ISSUE TITLE
zip::zip() is deprecated

### ISSUE THREAD

**Issue by Markus-Ewert** [awalker89/openxlsx#485] opened 2019-08-20 11:14 UTC
## Expected Behavior
No warning message

## Actual Behavior
The function openxlsx::saveWorkbook utilizes the zip function from the zip package which is soft-deprecated.

## sessionInfo()

  - Version of openxlsx: 4.1.0
  - Version of R: 3.5.3

**Comment by laubwolf** [comment] 2019-08-21 07:36
Duplicate of #454

**Closed as completed** 2019-08-27 08:53 UTC
