### ISSUE TITLE
Errors in saveWorkbook when some worksheets have comments and some don't

### ISSUE THREAD

**Issue by drjclark** [awalker89/openxlsx#158] opened 2016-02-29 15:54 UTC
When running the following code, based on the example from the createComment help page, I get an error message for "Error in comment_list[[i]] : subscript out of bounds".  However, when I remove the commenting around the writeComment function, the script executes without errors.
`wb <- createWorkbook()
sheet1=addWorksheet(wb, "Sheet 1")
c1 <- createComment(comment = "this is comment")
writeComment(wb, sheet1, col = "B", row = 10, comment = c1)
s1 <- createStyle(fontSize = 12, fontColour = "red", textDecoration = c("BOLD"))
s2 <- createStyle(fontSize = 9, fontColour = "black")
c2 <- createComment(comment = c("This Part Bold red\n\n", "This part black"), style = c(s1, s2))
writeComment(wb, 1, col = 6 , row = 3, comment = c2)
sheet2=addWorksheet(wb, "Sheet 2")
# writeComment(wb, 2, col = 6 , row = 3, comment = c2)

saveWorkbook(wb, file = "C:\Users\jclark\Documents\Strategic\Data Review and Profile Project\createCommentExample.xlsx", overwrite = TRUE)`

Also, I received a similar error when generating a 25 worksheet where the first and last worksheets had comments and all others did have comments.  The error message was slightly different in that case

> Error in sprintf("Override PartName...openxmlformatsofficedocument.spreadsheetml.comments+xml :
>   object fn not found

I suspect is has to do with the portion of $saveWorkbook with the following code

>    if (nComments > 0) {
>        for (i in 1:nSheets) {
>            if (length(comments[[i]]) > 0) 
>                fn <- sprintf("comments%s.xml", i)
>            Content_Types <<- c(Content_Types, sprintf("<Override PartName=\"/xl/%s\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml\"/>", 
>                 fn))

**Comment by awalker89** [comment] 2016-04-03 07:50
Which version of openxlsx are you using? The above code with and without the commented line works fine for me.

**Comment by drjclark** [comment] 2016-04-04 12:51
Thanks for looking into this.  Using Windows 7 version of R 3.2.0; openxlsx_3.0.0; Rcpp _0.11.6.  I updated to Rcpp_0.12.4 to make sure that wasn't the problem, and I get the same error messages.

FYI, I really love the package.  It's been incredibly useful to me.  Thanks you for making this.

**Comment by awalker89** [comment] 2016-04-05 22:44
Can you please update to the dev version of openxlsx - the issue is hopefully fixed now.
```
require("devtools")
install_github("awalker89/openxlsx")
```

**Closed** 2016-11-06 01:55 UTC
