### ISSUE TITLE
Problem with Hungarian multigraphs

### ISSUE THREAD

**Issue by balazsszalab** [awalker89/openxlsx#236] opened 2016-12-14 21:21 UTC
Hi!

I had an issue with writing several hundred columns of data into an Excel file correctly. I was able to open the file with LibreOffice Calc without any problem both in Ubuntu and in Windows, however when I tried to open it with MsExcel, Excel complained that the file is unreadable and after repairing the file, the content of two columns were erased. The erased columns were CS and GY which are multigraphs in the Hungarian alphabet. I tested if the data loss occurs at other compound letters like LY, TY, ZS etc. and I found that those columns are also corrupted.
I fixed the problem by setting my Hungarian locale to English for now and it worked, so MsExcel opens the file without error.
In addition, I figured out that if I use the writeData function only once before saving the workbook via saveWorkbook function, the error will not occur. However, if I call writeData more than once, the error will show up. I am not sure why.

**sessionInfo**:
> R version 3.2.3 (2015-12-10)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.1 LTS
> 
> locale:
>  [1] LC_CTYPE=hu_HU.UTF-8          LC_NUMERIC=C                 
>  [3] LC_TIME=hu_HU.UTF-8           LC_COLLATE=hu_HU.UTF-8       
>  [5] LC_MONETARY=hu_HU.UTF-8       LC_MESSAGES=hu_HU.UTF-8      
>  [7] LC_PAPER=hu_HU.UTF-8          LC_NAME=hu_HU.UTF-8          
>  [9] LC_ADDRESS=hu_HU.UTF-8        LC_TELEPHONE=hu_HU.UTF-8     
> [11] LC_MEASUREMENT=hu_HU.UTF-8    LC_IDENTIFICATION=hu_HU.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rkward_0.6.3
> 
> loaded via a namespace (and not attached):
> [1] tools_3.2.3       Rcpp_0.12.7       slam_0.1-32       numDeriv_2016.8-1
> [5] openxlsx_3.0.0    registry_0.3      ROI_0.2-1        

**This code generates a file that can be opened without error:**
> wb = openxlsx::createWorkbook()
> openxlsx::addWorksheet(wb, "test")
> openxlsx::writeData(wb, "test", matrix(1:2000,nrow=2), startCol = 1, startRow = 1, colNames = FALSE)
> openxlsx::saveWorkbook(wb, "testopenxlsx.xlsx", overwrite = TRUE)

**This code generates an xlsx file which can not be opened properly with MsExcel 2010 in Windows7:**
> wb = openxlsx::createWorkbook()
> openxlsx::addWorksheet(wb, "test")
> openxlsx::writeData(wb, "test", t(1:1000), startCol = 1, startRow = 1, colNames = FALSE)
> openxlsx::writeData(wb, "test", t(1:1000), startCol = 1, startRow = 2, colNames = FALSE)
> openxlsx::saveWorkbook(wb, "testopenxlsx.xlsx", overwrite = TRUE)

**This is my workaround:**
> Sys.setlocale("LC_CTYPE", "en_GB.UTF-8")
> Sys.setlocale("LC_COLLATE", "en_GB.UTF-8")
> wb = openxlsx::createWorkbook()
> openxlsx::addWorksheet(wb, "test")
> openxlsx::writeData(wb, "test", t(1:1000), startCol = 1, startRow = 1, colNames = FALSE)
> openxlsx::writeData(wb, "test", t(1:1000), startCol = 1, startRow = 2, colNames = FALSE)
> openxlsx::saveWorkbook(wb, "testopenxlsx.xlsx", overwrite = TRUE)
> Sys.setlocale("LC_CTYPE", "hu_HU.UTF-8")
> Sys.setlocale("LC_COLLATE", "hu_HU.UTF-8")

Best regards

Balazs
[testopenxlsx.xlsx](https://github.com/awalker89/openxlsx/files/652878/testopenxlsx.xlsx)

**Comment by awalker89** [comment] 2016-12-18 09:30
Hi thanks for the bug report.  When writing the second time the data inside the workbook needs to be sorted by the cell reference (e.g "A1", "B1", "CS1", "A2", "B2", ...).  This should be fixed in version 3.2.0.
Please update to the dev version using
```
devtools::install_github("awalker89/openxlsx")
```
I can't reproduce the error but I have replaced the code that I assume was causing this error.

**Closed** 2017-03-01 08:18 UTC
